name: kg-import 

channels:
  - conda-forge

dependencies:
  - python=3.10
  - jupyterlab
  - ipywidgets
  - papermill=2.4.0
  - pandas=2.1.1
  - py2neo=2021.2.3
  - monotonic=1.5
  - openjdk=17.0.8
  - python-dotenv=1.0.0
  - papermill

variables:
  # Neo4j local version
  DEMO_SERVER_URL: bolt://localhost:7687
  DEMO_SERVER_UN: neo4j
  DEMO_SERVER_PW: neo4jdemo
